### ISSUE TITLE
Discovery: the 'air qv' sensor appears to be a VOC sensor

### ISSUE THREAD

**Issue by Viss** [iprak/winix#60] opened 2023-10-22 20:55 UTC
I bought two winix 9800s a couple days ago, and I used this integration to hook them into home assistant. The first two things I was hoping to be able to do was "control them" and "get pm2.5 readings out". I noticed that theres an 'aqi' reading, and an 'air qv' reading, and neither are really pm2.5, and also, sadly, that i can only turn them on or off - i can't control them at all, sadly. 

I recently did a bunch of surface cleaning in one room and used a bunch of isopropyl alcohol from a spray bottle and that really made these air purifiers upset, but since I had already hooked them into home assistant, i saw this in the charts:

<img width="1384" alt="image" src="https://github.com/iprak/winix/assets/1756255/0b983e48-82e9-4ef0-bb51-ca0cbbc3fc2c">

its a VoC sensor!

**Comment by iprak** [comment] 2023-10-22 22:47
The purifier exposes some sensor values which are named as aqi and air_qvalue. They are not standard weather AQI values and just mimic the air quality metrics as shown in the app. Your hunch about them being VoC sensor is probably correct.

The integration has only been confirmed on a few selected models. On the surface, 9800 looks like C909 but I don't have that model to dig into it. The underlying library which integration is based on also only supports C545.

**Comment by Viss** [comment] 2023-10-22 23:17
happy to help do some r&d!
If there are api scrapers or if packet captures could help, let me know!
or if theres some script we can use to intercept its api calls

**Comment by iprak** [comment] 2023-10-22 23:26
Take a look at https://github.com/iprak/winix-1 CLI, the integration is based on that library. If the device can be turned on/off then maybe some error code is returned for other operations ?

**Comment by Viss** [comment] 2023-10-22 23:45
I installed the cli and "everythig just worked". I can fully control these units with this cli.
```
viss at cacodemon in ~/tools
% python3.11 -m pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (23.1.2)
Collecting pip
  Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 6.9 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-23.3.1
viss at cacodemon in ~/tools
% winixctl
usage: winixctl [-h] [--device DEVICE_SELECTOR] {login,refresh,devices,getstate,fan,power,mode,plasmawave} ...

Winix C545 Air Purifier Control

positional arguments:
  {login,refresh,devices,getstate,fan,power,mode,plasmawave}
    login               Authenticate Winix account
    refresh             Refresh account device metadata
    devices             List registered Winix devices
    getstate            Get device state
    fan                 Fan speed controls
    power               Power controls
    mode                Mode controls
    plasmawave          Plasmawave controls

options:
  -h, --help            show this help message and exit
  --device DEVICE_SELECTOR, -D DEVICE_SELECTOR
                        Device Index/Mac/Alias to use
viss at cacodemon in ~/tools
% winixctl login
You need to signup for a Winix account & associate your device in the phone app before using this.
Username (email): x
Password: x
Ok
viss at cacodemon in ~/tools
% winixctl devices
2 devices:
Device#0 (default) -------------------------------
      Device ID : x_********** (hidden)
            Mac : x
          Alias : Living room
       Location : ESDD

Device#1 -----------------------------------------
      Device ID : x_********** (hidden)
            Mac : x
          Alias : Playroom
       Location : ESDD

viss at cacodemon in ~/tools
% winixctl getstate
          power : on
           mode : manual
        airflow : low
            aqi : 3
         plasma : off
    filter_hour : 48
    air_quality : poor
     air_qvalue : 122
  ambient_light : 10

viss at cacodemon in ~/tools
% winixctl --device 0 getstate           
          power : on
           mode : manual
        airflow : low
            aqi : 2
         plasma : off
    filter_hour : 48
    air_quality : fair
     air_qvalue : 121
  ambient_light : 10
viss at cacodemon in ~/tools
% winixctl --device 1 getstate
          power : on
           mode : manual
        airflow : low
            aqi : 1
         plasma : off
    filter_hour : 48
    air_quality : good
     air_qvalue : 96
  ambient_light : 3

viss at cacodemon in ~/tools
% winixctl --device 0 fan high
ok
viss at cacodemon in ~/tools
% winixctl --device 0 fan turbo
ok
viss at cacodemon in ~/tools
% winixctl --device 0 fan high 
ok
viss at cacodemon in ~/tools
% winixctl --device 0 fan low 
ok
```

**Comment by iprak** [comment] 2023-10-23 00:23
Based on that, I would expect the devices to respond to commands from the integration correctly. maybe enable debug logging and see if something interesting shows up. You can run  this from Developer tools > SERVICES

```
service: logger.set_level
data:
  custom_components.winix: info
```

**Comment by Viss** [comment] 2023-10-23 00:29
well the issue isnt that the controls dont work - the issue is that they .. just arent present. 
I only have an on/off toggle. The plasmawave toggle or fan controls just arent even there
<img width="686" alt="image" src="https://github.com/iprak/winix/assets/1756255/e61f09a9-479b-4737-9ce5-2f01d901a803">

**Comment by iprak** [comment] 2023-10-23 00:50
The fan/plasma settings are part of the Fan card .. you should see them if you clicked on the fan icon for "Winix Living Room". There might be custom cards to show those options right away.

**Comment by iprak** [comment] 2023-10-24 23:21
Were you able to access the other options?

**Comment by Viss** [comment] 2023-10-24 23:40
sort of? the HA card is just a big vertical slider:
<img width="558" alt="image" src="https://github.com/iprak/winix/assets/1756255/a78de109-d718-4d37-9e84-8c5c55c22ea4">


and the plasmawave and other options appear as this sorta clunky dropdown-style selector:

<img width="380" alt="image" src="https://github.com/iprak/winix/assets/1756255/901a0777-cec8-4f49-b0d8-4e5904eaa3ac">


so the base functionality is there, but the card HA auto-selected is kinda garbage, and I would probably use mushroom cards to build a much sleeker, easier to read, more functional 'air purifier card' - but yes, the functionality exists and you can twiddle it in states or in templates. 

I'm almost 100% sure now the sensor this thing has is a VOC sensor, because the xiaomi I got does real pm2.5, and the other night cooking dinner i made a buuuuuunch of smoke (more or less intentionally). the xiamo went nuts. full red lines, full blast on the fan etc - the winix? it took a lot longer to notice, and if you dont have it on 'auto', it wont change its fan state when it detects 'bad air' - so I figure an ideal solution is to use one known-good pm2.5 sensor as the main trigger point, and fire requests at all the air filters in the house, ignoring the winix values.

**Comment by iprak** [comment] 2023-10-24 23:46
The Winix sensor is not PM2.5 .. I think you have options available to customize the appearance as desirable. I am closing this.

**Closed by iprak** 2023-10-24 23:46 UTC
